server.port=${PORT:8080}
logging.level.org.atmosphere=warn

vaadin.url-mapping=/_placeholder/*

vaadin.launch-browser=true

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,se.uddtronic.placeholder

server.error.whitelabel.enabled=false
